### ISSUE TITLE
[功能開發] 前端需要 end2end 測試框架

### ISSUE THREAD

**Issue by frohman-chang** [Game-as-a-Service/IncanGold#4]
### What problem does this feature solve?

可以獨立撰寫 end2end 測試
需在根目錄建立新的檔案夾管理
因爲此專案可能有不同的前端框架實作
希望做 end2end 測試時，可以測試到不同前端框架

### What does the proposed API look like?

```
root/
     end2end/
             vue-frontend/
                          when-user-leave-temple.spec
             angular-frontend/
             react-frontend/
```

**Comment by yi-luan** [comment]
後來發現Cypress已整合多方套件至CLI中
且有圖形化界面支援及語法親民等因素
因此考慮使用Cypress
